on:
  push:
    branches: master

jobs:
  docker-build-push-action:
    strategy:
      fail-fast: false
      matrix:
        registry: [ghcr.io, docker.pkg.github.com]
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ matrix.registry }}/${{ github.repository_owner }}/docker-build-push-action-test/app3:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: token
          password: ${{ secrets.PACKAGES_TOKEN }}
      -
         run: echo "FROM alpine" > Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

  docker-build-push:
    strategy:
      fail-fast: false
      matrix:
        registry: [ghcr.io, docker.pkg.github.com]
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ matrix.registry }}/${{ github.repository_owner }}/docker-build-push-action-test/app2:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        run: docker login ${{ matrix.registry }} -u token -p ${{ secrets.PACKAGES_TOKEN }}
      -
         run: echo "FROM alpine" > Dockerfile
      -
        name: Build
        run: docker build . -t ${{ env.IMAGE }}
      -
        name: Push
        run: docker push ${{ env.IMAGE }}
