on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.pkg.github.com/${{ github.repository }}/app:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: token
          password: ${{ github.token }}
      -
         run: echo "FROM alpine" > Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
